#include <stdio.h>
#include <string.h>
#include "product.h"

int product_find_by_barcode(Database *db, const char *barcode, ProductPackage *result){
    const char *sql =
        "SELECT "
        "p.id, "
        "pp.id, "
        "pp.barcode, "
        "p.name, "
        "p.brand, "
        "p.inventory_unit, "
        "pp.package_quantity "
        "FROM product_packages pp "
        "JOIN products p ON pp.product_id = p.id "
        "WHERE pp.barcode = ?;";

    sqlite3_stmt *stmt = NULL;

    int rc = sqlite3_prepare_v2(
        db->connection,
        sql,
        -1,
        &stmt,
        NULL
    );

    if (rc != SQLITE_OK)
    {
        fprintf(stderr,
                "Failed to prepare barcode lookup: %s\n",
                sqlite3_errmsg(db->connection));

        return -1;
    }

    sqlite3_bind_text(
        stmt,
        1,
        barcode,
        -1,
        SQLITE_TRANSIENT
    );

    rc = sqlite3_step(stmt);

    if (rc == SQLITE_ROW)
    {
        result->product_id =
            sqlite3_column_int(stmt, 0);

        result->package_id =
            sqlite3_column_int(stmt, 1);

        snprintf(
            result->barcode,
            sizeof(result->barcode),
            "%s",
            sqlite3_column_text(stmt, 2)
        );

        snprintf(
            result->product_name,
            sizeof(result->product_name),
            "%s",
            sqlite3_column_text(stmt, 3)
        );

        snprintf(
            result->brand,
            sizeof(result->brand),
            "%s",
            sqlite3_column_text(stmt, 4)
        );

        snprintf(
            result->inventory_unit,
            sizeof(result->inventory_unit),
            "%s",
            sqlite3_column_text(stmt, 5)
        );

        result->package_quantity =
            sqlite3_column_int(stmt, 6);

        sqlite3_finalize(stmt);

        return 0;
    }

    if (rc == SQLITE_DONE)
    {
        sqlite3_finalize(stmt);
        return 1;
    }

    fprintf(stderr,
            "Barcode lookup failed: %s\n",
            sqlite3_errmsg(db->connection));

    sqlite3_finalize(stmt);

    return -1;
}


int product_create_with_package(
    Database *db,
    const char *name,
    const char *brand,
    const char *inventory_unit,
    int low_stock_threshold,
    int auto_add_grocery,
    const char *barcode,
    int package_quantity,
    int *product_id_out
) {
    sqlite3_stmt *stmt = NULL;
    int rc;

    if (
        db == NULL ||
        db->connection == NULL ||
        name == NULL ||
        inventory_unit == NULL ||
        barcode == NULL ||
        product_id_out == NULL ||
        low_stock_threshold < 0 ||
        package_quantity <= 0
    ) {
        return -1;
    }

    rc = sqlite3_exec(
        db->connection,
        "BEGIN;",
        NULL,
        NULL,
        NULL
    );

    if (rc != SQLITE_OK) {
        return -1;
    }

    const char *product_sql =
        "INSERT INTO products "
        "(name, brand, inventory_unit, "
        " low_stock_threshold, auto_add_grocery) "
        "VALUES (?, ?, ?, ?, ?);";

    rc = sqlite3_prepare_v2(
        db->connection,
        product_sql,
        -1,
        &stmt,
        NULL
    );

    if (rc != SQLITE_OK) {
        goto rollback;
    }

    sqlite3_bind_text(
        stmt, 1, name, -1, SQLITE_TRANSIENT
    );

    /*
     * Empty brand becomes SQL NULL.
     */
    if (brand != NULL && brand[0] != '\0') {
        sqlite3_bind_text(
            stmt, 2, brand, -1, SQLITE_TRANSIENT
        );
    }
    else {
        sqlite3_bind_null(stmt, 2);
    }

    sqlite3_bind_text(
        stmt,
        3,
        inventory_unit,
        -1,
        SQLITE_TRANSIENT
    );

    sqlite3_bind_int(
        stmt,
        4,
        low_stock_threshold
    );

    sqlite3_bind_int(
        stmt,
        5,
        auto_add_grocery ? 1 : 0
    );

    rc = sqlite3_step(stmt);

    if (rc != SQLITE_DONE) {
        goto rollback;
    }

    sqlite3_finalize(stmt);
    stmt = NULL;

    /*
     * SQLite tells us the ID generated by the
     * INSERT we just performed.
     */
    sqlite3_int64 product_id =
        sqlite3_last_insert_rowid(db->connection);

    const char *package_sql =
        "INSERT INTO product_packages "
        "(product_id, barcode, package_quantity) "
        "VALUES (?, ?, ?);";

    rc = sqlite3_prepare_v2(
        db->connection,
        package_sql,
        -1,
        &stmt,
        NULL
    );

    if (rc != SQLITE_OK) {
        goto rollback;
    }

    sqlite3_bind_int64(
        stmt,
        1,
        product_id
    );

    sqlite3_bind_text(
        stmt,
        2,
        barcode,
        -1,
        SQLITE_TRANSIENT
    );

    sqlite3_bind_int(
        stmt,
        3,
        package_quantity
    );

    rc = sqlite3_step(stmt);

    if (rc != SQLITE_DONE) {
        goto rollback;
    }

    sqlite3_finalize(stmt);
    stmt = NULL;

    rc = sqlite3_exec(
        db->connection,
        "COMMIT;",
        NULL,
        NULL,
        NULL
    );

    if (rc != SQLITE_OK) {
        sqlite3_exec(
            db->connection,
            "ROLLBACK;",
            NULL,
            NULL,
            NULL
        );

        return -1;
    }

    *product_id_out = (int)product_id;

    return 0;


rollback:

    if (stmt != NULL) {
        sqlite3_finalize(stmt);
    }

    sqlite3_exec(
        db->connection,
        "ROLLBACK;",
        NULL,
        NULL,
        NULL
    );

    return -1;
}

int product_add_package(
    Database *db,
    int product_id,
    const char *barcode,
    int package_quantity
) {
    if (
        db == NULL ||
        db->connection == NULL ||
        product_id <= 0 ||
        barcode == NULL ||
        barcode[0] == '\0' ||
        package_quantity <= 0
    ) {
        return -1;
    }

    const char *sql =
        "INSERT INTO product_packages "
        "(product_id, barcode, package_quantity) "
        "VALUES (?, ?, ?);";

    sqlite3_stmt *stmt = NULL;

    int rc = sqlite3_prepare_v2(
        db->connection,
        sql,
        -1,
        &stmt,
        NULL
    );

    if (rc != SQLITE_OK) {
        fprintf(
            stderr,
            "Failed to prepare package insert: %s\n",
            sqlite3_errmsg(db->connection)
        );

        return -1;
    }

    sqlite3_bind_int(
        stmt,
        1,
        product_id
    );

    sqlite3_bind_text(
        stmt,
        2,
        barcode,
        -1,
        SQLITE_TRANSIENT
    );

    sqlite3_bind_int(
        stmt,
        3,
        package_quantity
    );

    rc = sqlite3_step(stmt);

    if (rc != SQLITE_DONE) {
        fprintf(
            stderr,
            "Failed to add product package: %s\n",
            sqlite3_errmsg(db->connection)
        );

        sqlite3_finalize(stmt);

        return -1;
    }

    sqlite3_finalize(stmt);

    return 0;
}


int product_list(
    Database *db,
    Product *products,
    int max_products,
    int *product_count
) {
    if (
        db == NULL ||
        db->connection == NULL ||
        products == NULL ||
        product_count == NULL ||
        max_products <= 0
    ) {
        return -1;
    }

    const char *sql =
        "SELECT id, name, brand, inventory_unit "
        "FROM products "
        "ORDER BY name;";

    sqlite3_stmt *stmt = NULL;

    int rc = sqlite3_prepare_v2(
        db->connection,
        sql,
        -1,
        &stmt,
        NULL
    );

    if (rc != SQLITE_OK) {
        fprintf(
            stderr,
            "Failed to prepare product list: %s\n",
            sqlite3_errmsg(db->connection)
        );

        return -1;
    }

    int count = 0;

    while (
        count < max_products &&
        (rc = sqlite3_step(stmt)) == SQLITE_ROW
    ) {
        Product *product = &products[count];

        product->id = sqlite3_column_int(stmt, 0);

        const unsigned char *name =
            sqlite3_column_text(stmt, 1);

        const unsigned char *brand =
            sqlite3_column_text(stmt, 2);

        const unsigned char *unit =
            sqlite3_column_text(stmt, 3);

        snprintf(
            product->name,
            sizeof(product->name),
            "%s",
            name != NULL ? (const char *)name : ""
        );

        snprintf(
            product->brand,
            sizeof(product->brand),
            "%s",
            brand != NULL ? (const char *)brand : ""
        );

        snprintf(
            product->inventory_unit,
            sizeof(product->inventory_unit),
            "%s",
            unit != NULL ? (const char *)unit : ""
        );

        count++;
    }

    if (rc != SQLITE_DONE && count < max_products) {
        fprintf(
            stderr,
            "Failed while reading product list: %s\n",
            sqlite3_errmsg(db->connection)
        );

        sqlite3_finalize(stmt);

        return -1;
    }

    sqlite3_finalize(stmt);

    *product_count = count;

    return 0;
}